[WIP] 🎃 Halloween sprint
frontend/toolbox-reader pull request #30
Opened 2017-10-31 14:32 UTC by Yago

2017-11-01 15:44 UTC, Yago commented
Work with https://github.com/frontend/toolbox-utils/pull/20

Each feature on each commits 😉

2017-11-02 08:38 UTC, tonifisler submitted a review, later dismissed
Ok for me!! Awesome

2017-11-02 08:38 UTC, tonifisler commented on src/components/App/App.scss
> +  flex: 0 0 60px;
I think the toolbar would be more useful with `position: fixed;`.

2017-11-02 13:11 UTC, Yago commented
@tonifisler I add responsive layout too 😉

2017-11-02 15:01 UTC, tonifisler requested changes

2017-11-02 15:01 UTC, tonifisler commented on src/components/App/App.scss
> +  width: 50px;
Should be `60px`
<img width="337" alt="screen shot 2017-11-02 at 16 00 50" src="https://user-images.githubusercontent.com/1708450/32332965-09a080d6-bfe7-11e7-9ff9-6d8f992a7d11.png">

2017-11-02 15:58 UTC, Yago commented on src/components/App/App.scss
> +  width: 50px;
I found that weird too when my Chrome show me that 50px is better 😅

2017-11-02 16:01 UTC, Yago commented on src/components/App/App.scss
> +  width: 50px;
`box-sizing` ¯\_(ツ)_/¯

2017-11-03 15:33 UTC, merged